package com.kasir.manajemenkasir.service;

import com.kasir.manajemenkasir.model.Barang;
import com.kasir.manajemenkasir.model.Toko;
import com.kasir.manajemenkasir.repository.BarangRepository;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class BarangService {
    private final BarangRepository barangRepository;

    public BarangService(BarangRepository barangRepository) {
        this.barangRepository = barangRepository;
    }

    public List<Barang> getAllBarang(Toko toko) {
        return barangRepository.findByToko(toko);
    }

    public int hitungTotalBarang(Toko toko) {
        return getAllBarang(toko).size();
    }

    public int hitungTotalStok(Toko toko) {
        int total = 0;
        for (Barang barang : getAllBarang(toko)) {
            total += barang.getStok();
        }
        return total;
    }

    public Barang getBarangById(int idBarang) {
        return barangRepository.findById(idBarang).orElse(null);
    }

    public void tambahBarang(Barang barang) {
        // ID will be automatically generated by the database
        barang.setIdBarang(0);
        barangRepository.save(barang);
    }

    public void updateBarang(int idBarang, Barang barangBaru) {
        Barang barang = getBarangById(idBarang);

        if (barang != null) {
            barang.setNamaBarang(barangBaru.getNamaBarang());
            barang.setKategori(barangBaru.getKategori());
            barang.setHargaModal(barangBaru.getHargaModal());
            barang.setHarga(barangBaru.getHarga());
            barang.setStok(barangBaru.getStok());
            barang.setGambar(barangBaru.getGambar());
            barangRepository.save(barang);
        }
    }

    public void hapusBarang(int idBarang) {
        barangRepository.deleteById(idBarang);
    }

    public List<Barang> getStokMenipis(Toko toko) {
        return getAllBarang(toko).stream()
                .filter(b -> b.getStok() <= 5)
                .collect(java.util.stream.Collectors.toList());
    }
}